resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/ni3ol/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-scho
